<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 08/16/2007 - 3:44am
 * View: BibleStudyList
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   BibleStudyList, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_resouce_link_url -- 
 * $field_resouce_link_url_label -- The assigned label for $field_resouce_link_url
 *
 * This function goes in your views-list-BibleStudyList.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-BibleStudyList.css');
  
  ?>

<div class="view-field view-data-field-resouce-link-url">
  <?php print $field_resouce_link_url?>
</div>